<?php $comments = $this->driver->getComments(); ?>
<?php if (empty($comments) || count($comments) == 0): ?>
  <div class="alert alert-info"><?=$this->transEsc('Be the first to leave a comment')?>!</div>
<?php else: ?>
  <?php foreach ($comments as $comment): ?>
    <div class="comment">
      <div class="comment-name">
        <strong><?=null === $comment[0]->getUser()->getId() ? $this->transEsc('comment_anonymous_user') : $this->escapeHtml(trim($comment['firstname'] . ' ' . $comment['lastname']))?></strong><br/>
        <small>
          <?=$this->escapeHtml($comment[0]->getCreated()->format('Y-m-d H:i:s'))?>
          <?php if (($user = $this->auth()->isLoggedIn()) && $comment[0]->getUser()->getId() == $user->id): ?>
            <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'DeleteComment'))?>?delete=<?=urlencode($comment[0]->getId())?>" id="recordComment<?=$this->escapeHtml($comment[0]->getId())?>" class="delete"><?=$this->transEsc('Delete')?></a>
          <?php endif; ?>
        </small>
      </div>
      <div class="comment-text">
        <?=$this->escapeHtml($comment[0]->getComment())?>
      </div>
      <?php if ($this->driver->isRatingAllowed()): ?>
        <div class="comment-rating">
          <?php $ratingData = $this->driver->getRatingData($comment[0]->getUser()->getId()); ?>
          <?php if ($ratingData['count']): ?>
            <?=$this->render('Helpers/star-rating.phtml', ['readonly' => true, 'ratingData' => $ratingData]);?>
          <?php endif; ?>
        </div>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
